version: "3"
services: 
  app:
    build: ./app/
    image: event-planner-api:latest 
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database
  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - database
  database:
    image: postgres:alpine
    volumes:
      - ./database:/var/lib/postgresql/data 
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure


