version: "3"
services: 
  app:
    build: ./app/
    image: event-planner-api:latest 
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - database
  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - database
      - rabbitmq  

  database:
    image: postgres:alpine
    volumes:
      - ./database:/var/lib/postgresql/data 
    expose:
      - 5432
    environment:
      - POSTGRES_DB=service_ml_2
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"  
      - "5672:5672"    
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}  
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}  
  worker:
    build:
      context: ./app/  
      dockerfile: Dockerfile_worker  
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - database  
    restart: always


